### ISSUE TITLE
ReferenceError: require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by JCZuurmond** [opt-nc/setup-duckdb-action#49]
I get the following error in [this CI run](https://github.com/godatadriven/github-contributions/actions/runs/5973683694/job/16206399344):

```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/_actions/opt-nc/setup-duckdb-action/v1.0.0/dist/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/_actions/opt-nc/setup-duckdb-action/v1.0.0/webpack:/setup-duckdb-action/index.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5)
    at handleMainPromise (node:internal/modules/run_main:65:12)
```

I get this error in step:

```
      - uses: opt-nc/setup-duckdb-action@v1.0.0
        with:
          version: v0.8.1
```

**Comment by adriens** [comment]
Hi @JCZuurmond , thanks for reporting this to us : would you share a public repo with the exception occuring in the CI ?

**Comment by adriens** [comment]
Waiting for issuer feedback
:pause_button:

**Comment by JCZuurmond** [comment]
[Here](https://github.com/godatadriven/github-contributions/commit/312f691a6acafa38a4829a58596d0b8cab0d6b29) you find the action that references this step. The CI run that failed is mentioned above.

**Comment by adriens** [comment]
@mbarre , here is the `yaml` : 

```yaml
name: Upload duckdb database to Motherduck

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Run dbt
    types:
      - completed

env:
  DUCKDB_DATABASE: github_contributions
  DUCKDB_PATH: github_contributions.duckdb
  DUCKDB_VERSION: v0.8.1

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download duckdb
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ${{ env.DUCKDB_PATH }}
          workflow: dbt.yml
          workflow_conclusion: success

      - uses: opt-nc/setup-duckdb-action@v1.0.0
        with:
          version: ${{ env.DUCKDB_VERSION }}

      - name: Upload duckdb database to Motherduck
        run: |
          duckdb -c ".open md:" -s "DROP DATABASE IF EXISTS ${{ env.DUCKDB_DATABASE }}"
          duckdb -c ".open md:" -s "CREATE DATABASE ${{ env.DUCKDB_DATABASE }} FROM '${{ env.DUCKDB_PATH }}'"
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
```

**Comment by adriens** [comment]
btw @JCZuurmond , cool, I see that ou use both MD and dbt :sunglasses:

**Comment by adriens** [comment]
@JCZuurmond , here is how we use the action internally, many (many) times per day:

```yaml
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: 🧪 Check data


on: [pull_request, push]

jobs:
  test:
    name: 🧪 Verify data
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: ⚙️ Install DuckDB
        uses: opt-nc/setup-duckdb-action@v1.0.4
        with:
          version: ${{ vars.VERSION_DUCKDB}}


      - name : 🕵️‍♂️ Check data integrity
        run: |
          duckdb carto.duckdb < duck.sql
```
